# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerebrium" do
  name "cerebrium"
  desc "CLI for deploying and managing Cerebrium apps"
  homepage "https://www.cerebrium.ai"
  version "2.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerebrium"

  on_macos do
    on_intel do
      url "https://github.com/CerebriumAI/cerebrium/releases/download/v#{version}/cerebrium_cli_darwin_amd64.tar.gz"
      sha256 "887041b7f1ec7048dbaa46a97602af1c2a3fc1291fb0c588642d8f26d7c1bd5e"
    end
    on_arm do
      url "https://github.com/CerebriumAI/cerebrium/releases/download/v#{version}/cerebrium_cli_darwin_arm64.tar.gz"
      sha256 "48dfc107225f0a18a478908dffb82272c1e8b0e3203a75042d16f86f2093784d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CerebriumAI/cerebrium/releases/download/v#{version}/cerebrium_cli_linux_amd64.tar.gz"
      sha256 "410129b99837c894875c582607b2b4b321800487952c546ba619443115043829"
    end
    on_arm do
      url "https://github.com/CerebriumAI/cerebrium/releases/download/v#{version}/cerebrium_cli_linux_arm64.tar.gz"
      sha256 "b3be9af3a82619904fcfcbd4af68781cd679565f53db51eed6b0a9155f251fcd"
    end
  end

  # No zap stanza required
end
