# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerebrium" do
  version "2.2.6"

  on_macos do
    on_intel do
      sha256 "423e223e372b95bc57461f5a4960c83396504e8e8681235740233ddb48b8554d"
      url "https://github.com/CerebriumAI/cerebrium/releases/download/v#{version}/cerebrium_cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "90f672a02af4e4fba2feff7479193c81415a5d0b84fc82ed2f416abf8c99a0b7"
      url "https://github.com/CerebriumAI/cerebrium/releases/download/v#{version}/cerebrium_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24377c3d0a99538d6e6a02da0cd579c525d68e11f7138e2417502bb40d5b10cb"
      url "https://github.com/CerebriumAI/cerebrium/releases/download/v#{version}/cerebrium_cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b29e0301c5d37557c02d8248300f051dcf8d03c4dbab31bdcfaf93e335373225"
      url "https://github.com/CerebriumAI/cerebrium/releases/download/v#{version}/cerebrium_cli_linux_arm64.tar.gz"
    end
  end

  name "cerebrium"
  desc "CLI for deploying and managing Cerebrium apps"
  homepage "https://www.cerebrium.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerebrium"

  # No zap stanza required

end
